### ISSUE TITLE
chenkovsky/docopt.cr broken my code.

### ISSUE THREAD

**Issue by zw963** [ralsina/polydocopt#1]
https://github.com/chenkovsky/docopt.cr broken my code, why not switch to yours fork?

https://forum.crystal-lang.org/t/wired-compiler-error-bug-called-type-id-for-array-config-class-crystal-virtualmetaclasstype-exception/7400

**Comment by ralsina** [comment]
By all means, switch to my fork, I created it because docopt was causing
weird things in my code too :-)

**Comment by zw963** [comment]
Okay, i will create a PR for this.

**Comment by zw963** [comment]
#2

**Comment by zw963** [comment]
Thank you, i consider release a new version is necessary?

**Comment by ralsina** [comment]
Yes, will do it in a bit.

**Comment by ralsina** [comment]
Done :-)

**Comment by zw963** [comment]
Thanks.
